#!/usr/bin/bash
set -e

sudo apt install curl nmap

# Installing Proxy
firefox https://portswigger.net/burp/communitydownload
firefox https://caido.io/download

# Installing Go and Gobuster
if [[ -z "go version" ]];
then
    echo "It looks like go is not installed. Follows this instruction to install go"
    firefox https://go.dev/doc/install
else
    echo "Go is installed. Installing Gobuster"
    go install github.com/OJ/gobuster/v3@latest
fi
