#!/usr/bin/bash

sudo pacman -S sddm qt6-svg qt6-virtualkeyboard qt6-multimedia-ffmpeg

git clone https://github.com/stepanzubkov/where-is-my-sddm-theme $HOME/.local/src/where-is-my-sddm-theme
sudo cp -r $HOME/.local/src/where-is-my-sddm-theme/where_is_my_sddm_theme /usr/share/sddm/themes


# sh -c "$(curl -fsSL https://raw.githubusercontent.com/keyitdev/sddm-astronaut-theme/master/setup.sh)"

# https://github.com/stepanzubkov/where-is-my-sddm-theme
# or https://github.com/Keyitdev/sddm-astronaut-theme?tab=readme-ov-file#manual-installation
