[window]
decorations = "Full"
opacity = 1
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 11.0
offset = { x = 0, y = 2 }

[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml",
]
